"""empty message

Revision ID: 1b9a2c892aae
Revises: 
Create Date: 2020-03-22 14:05:23.301897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9a2c892aae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('limitations', sa.String(length=120), nullable=True))
    op.drop_column('record', 'limitation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('limitation', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('record', 'limitations')
    # ### end Alembic commands ###
